services:
  opensearch:
    image: opensearchproject/opensearch:3.0.0
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      # Disable JVM heap memory swapping
      - bootstrap.memory_lock=true
      # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - plugins.security.ssl.http.enabled=false
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-network
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  logstash:
    build:
      context: ./logstash
    container_name: logstash
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    depends_on:
      - opensearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5045:5045"
      - "5046:5046"
    networks:
      - opensearch-network
    restart: unless-stopped

networks:
  opensearch-network:

volumes:
  opensearch-data:
