stages:
  generatePlans:
    matrix:
      model: ${models}
      repetition: ${repetitions}
    cmd: ../gradlew runExperiment --args="--model-id ${item.model} --run-id ${item.model}-${item.repetition} --timeout-millis ${timeout} --lm-server-url ${provider} --temperature ${temperature} --max-tokens ${maxTokens} --log-dir experiments --log-to-file"
    outs:
      - experiments/${item.model}-${item.repetition}:
          persist: true

  computeMetrics:
    matrix:
      model: ${models}
      repetition: ${repetitions}
    cmd: ../gradlew analyzePGP --args="--exp-dir experiments/${item.model}-${item.repetition} --metrics-dir metrics/${item.model}-${item.repetition} --compute-metrics"
    deps:
      - experiments/${item.model}-${item.repetition}
    outs:
      - metrics/${item.model}-${item.repetition}:
          persist: true
