stages:
  testGeneration:
    matrix:
      model: ${models}
      dataset: ${datasets}
    cmd: ../gradlew runExperiment --quiet --args="
      --model-id=${item.model}
      --log-dir=experiments
      --log-to-console
      --log-to-file"
    outs:
      - experiments:
          persist: true