stages:
  generatePlans:
    matrix:
      temperature: ${temperatures}
      model: ${models}
      repetition: ${repetitions}
      prompt: ${promptTypes}
    cmd: ../gradlew runExperiment --args="--model-id ${item.model} --prompt-type ${item.prompt} --run-id ${item.model}-${item.repetition}-${item.prompt}-${item.temperature} --timeout-millis ${timeout} --lm-server-url ${provider} --temperature ${item.temperature} --max-tokens ${maxTokens} --log-dir experiments --log-to-file"
    outs:
      - experiments/${item.model}-${item.repetition}-${item.prompt}-${item.temperature}/:
          persist: true

  computeMetrics:
    matrix:
      temperature: ${temperatures}
      model: ${models}
      repetition: ${repetitions}
      prompt: ${promptTypes}
    cmd: ../gradlew analyzePGP --args="--exp-dir experiments/${item.model}-${item.repetition}-${item.prompt}-${item.temperature} --metrics-dir metrics/${item.model}-${item.repetition}-${item.prompt}-${item.temperature} --compute-metrics --retrieve-generation-data"
    deps:
      - experiments/${item.model}-${item.repetition}-${item.prompt}-${item.temperature}/
    outs:
      - metrics/${item.model}-${item.repetition}-${item.prompt}-${item.temperature}/:
          persist: true
