stages:
  testGeneration:
    matrix:
      model: ${models}
    cmd: >-
      ./runner.sh
      "${item.model}"
      "${repetitions}"
      "${timeout}"
      "${provider}"
      "${temperature}"
      "${maxTokens}"
    outs:
      - experiments/${item.model}:
          persist: true