stages:
  testGeneration:
    matrix:
      model: ${models}
    cmd: >-
      ../gradlew runExperiments
      -Pmodel="${item.model}"
      -Prepetitions="${repetitions}"
      -PtimeoutSeconds="${timeout}"
      -Pprovider="${provider}"
      -Ptemperature="${temperature}"
      -PmaxTokens="${maxTokens}"
    outs:
      - experiments/${item.model}:
          persist: true
