models: [
  "openai/gpt-4.1",
  "deepseek/deepseek-chat-v3-0324",
  "anthropic/claude-3.7-sonnet:thinking",
  "google/gemini-2.5-pro-preview-03-25"
]
temperature: 0.5
maxTokens: 4096
repetitions: 1
timeout: 5
provider: "https://testsadsasa.ai/api/v1/"
