models: [
  "deepseek/deepseek-chat-v3-0324:free",
  "openai/gpt-4.1",
  "anthropic/claude-sonnet-4",
  "google/gemini-2.5-flash",
#  "mistralai/devstral-small:free",
#  "google/gemma-3-27b-it:free"
#  "qwen/qwen-2.5-coder-32b-instruct:free"
#  "qwen/qwen-2.5-72b-instruct:free",
#  "meta-llama/llama-3.3-70b-instruct:free"
]
temperatures: [0.1, 0.5, 0.9]
maxTokens: 2048
promptTypes: ["prompt_with_hints", "prompt_without_hints", "prompt_with_hints_and_remarks"]
repetitions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
timeout: 50000
provider: "https://openrouter.ai/api/v1/"